name: Build and Release Contract

on:
  workflow_call:
    inputs:
      contract_dirs:
        description: 'JSON-encoded array of relative path to the contract directories'
        type: string
        required: true
        default: '[""]'
      release_name: 
        description: 'Name for the release'
        required: true
        type: string
      release_description:
        description: 'Description for the release'
        required: false
        type: string
    secrets:
      release_token:
        description: 'Github token'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        directory: ${{ fromJson(inputs.contract_dirs) }}
    steps:
      - name: Determine checkout directory
        run: |
          if [[ "${{ matrix.directory }}" == "" ]]; then
            echo "CHECKOUT_DIRECTORY=root" >> $GITHUB_ENV
          else
            echo "CHECKOUT_DIRECTORY=${{ matrix.directory }}" >> $GITHUB_ENV
          fi

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ${{ strategy.job-index }}

      - name: Run docker container
        working-directory: ${{ github.workspace }}/${{ strategy.job-index }}
        run: docker run --rm -e CONTRACT_DIR=${{ matrix.directory }} -v "${{ github.workspace }}/${{ strategy.job-index }}:/inspector/home" ghcr.io/hawthorne-abendsen/contract-build-workflow:v0.6.3

      - name: Get wasm file name
        working-directory: ${{ github.workspace }}/${{ strategy.job-index }}
        run: |
          cd ${{ github.workspace }}/${{ strategy.job-index }}/release
          wasm_file=$(find -type f -name "*.wasm")
          cp $wasm_file ${{ github.workspace }}/${{ strategy.job-index }}
          echo "WASM_FILE_NAME=$(basename $wasm_file)" >> $GITHUB_ENV  
          echo "WASM_FILE_SHA256=$(sha256sum $wasm_file | cut -d ' ' -f 1)" >> $GITHUB_ENV 
      
      - name: Wasm file from directory ${{ matrix.directory }} with hash ${{ env.WASM_FILE_SHA256 }} created
        run: echo ${{ env.WASM_FILE_NAME }}
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.WASM_FILE_NAME }}
          path: ${{ github.workspace }}/${{ strategy.job-index }}/release/${{ env.WASM_FILE_NAME }}
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
        
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.release_name }}
          draft: false
          prerelease: false
          body: ${{ inputs.release_description }}
          files: '**/*.wasm'
          token: ${{ secrets.release_token }}