name: Build and Optimize Contract

on:
  workflow_call:
    inputs:
      contract_dir:
        description: 'Relative path to the contract directory'
        type: string
        required: false
      release_name: 
        description: 'Name for the release'
        required: true
        type: string
      release_description:
        description: 'Description for the release'
        required: false
        type: string
    secrets:
      release_token:
        description: 'Github token'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run docker container
        run: docker run --rm -e CONTRACT_DIR=${{ inputs.contract_dir }} -v "${{ github.workspace }}:/inspector/home" ghcr.io/hawthorne-abendsen/contract-build-workflow:v0.6.2

      - name: Get wasm file name
        run: |
          cd ${{ github.workspace }}/release
          wasm_file=$(find -type f -name "*.wasm")
          echo "WASM_FILE_NAME=$(basename $wasm_file)" >> $GITHUB_ENV  
          echo "WASM_FILE_SHA256=$(sha256sum $wasm_file | cut -d ' ' -f 1)" >> $GITHUB_ENV 

      - name: Create release ${{ env.WASM_FILE_SHA256 }}
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.release_token }}
        with:
          tag_name: ${{ inputs.release_name }}
          draft: false
          prerelease: false
          body: ${{ inputs.release_description }}
          files: ${{ github.workspace }}/release/${{ env.WASM_FILE_NAME }}