name: Build and Release Contract

on:
  workflow_call:
    inputs:
      ralative_path:
        description: 'Relative path to the working directory'
        type: string
        required: false
      make_target:
        description: 'Make target for the contract'
        type: string
        required: false
      package:
        description: 'Package to build'
        type: string
        required: false
      release_name: 
        description: 'Name for the release'
        required: true
        type: string
      release_description:
        description: 'Description for the release'
        required: false
        type: string
    secrets:
      release_token:
        description: 'Github token'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Set directory names and paths
        run: |
          build_dir_name="build_"$(openssl rand -base64 8 | tr -d '/+=' | head -c 8)
          echo "BUILD_DIR_NAME=$build_dir_name" >> $GITHUB_ENV
          echo "BUILD_DIR_PATH=${{ github.workspace }}/$build_dir_name" >> $GITHUB_ENV

      - name: Verify that checkout directory doesn't exist
        run: |
          if [[ -d ${{ env.BUILD_DIR_PATH }} ]]; then
            echo "Directory ${{ env.BUILD_DIR_PATH }} already exists"
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ${{ env.BUILD_DIR_NAME }}

      - name: Run docker container
        working-directory: ${{ env.BUILD_DIR_PATH }}
        run: docker run --rm -e RELATIVE_PATH=${{ inputs.ralative_path }} -e MAKE_TARGET=${{ inputs.make_target }} -e PACKAGE=${{ inputs.package }} -v "${{ env.BUILD_DIR_PATH }}:/inspector/home" ghcr.io/hawthorne-abendsen/contract-build-workflow:latest

      - name: Get wasm file name
        working-directory: ${{ env.BUILD_DIR_PATH }}
        run: |
          cd ${{ env.BUILD_DIR_PATH }}/compilation_workflow_release
          wasm_file=$(find -type f -name "*.wasm")
          cp $wasm_file ${{ env.BUILD_DIR_PATH }}
          echo "WASM_FILE_NAME=$(basename $wasm_file)" >> $GITHUB_ENV  
          echo "WASM_FILE_SHA256=$(sha256sum $wasm_file | cut -d ' ' -f 1)" >> $GITHUB_ENV 
      
      - name: Output WASM ${{ env.WASM_FILE_SHA256 }} from ${{ env.CONTRACT_DIR_NAME }}
        run: echo ${{ env.WASM_FILE_NAME }}
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.WASM_FILE_NAME }}
          path: ${{ env.BUILD_DIR_PATH }}/compilation_workflow_release/${{ env.WASM_FILE_NAME }}
          if-no-files-found: error
      
      - name: Build release name
        run: |
          if [ -n "${{ inputs.relative_path }}" ]; then
            relative_path="_${{ inputs.relative_path }}"
          else
            relative_path=""
          fi
          if [ -n "${{ inputs.package }}" ]; then
            package="_${{ inputs.package }}"
          else
            package=""
          fi
          tag=${{ inputs.release_name }}${relative_path}${package}_${{ env.WASM_FILE_NAME }}
          cleaned_tag=$(echo "$tag" | sed 's/\W\+/_/g')
          echo "TAG_NAME=$cleaned_tag" >> $GITHUB_ENV
        
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          body: ${{ inputs.release_description }}
          files: '${{ env.BUILD_DIR_PATH }}/compilation_workflow_release/${{ env.WASM_FILE_NAME }}'
          token: ${{ secrets.release_token }}